### ISSUE TITLE
include模板并传入数据时不支持{{}}这种写法吗？

### ISSUE THREAD

**Issue by fantasy525** [aui/art-template-loader#10]
example中的例子：`<% include('./header.art', {
      title: title
}) %>
我想这样写就会报错
{{include('./header.art',{title:title})}}`
错误提示：
`ERROR in ./include/index.art
Module build failed: TypeError: Cannot read property 'name' of undefined
    at Controller.enter (E:\webpack\art-templte-loader\node_modules\art-template\lib\precompile.js:143:48)
    at Controller.__execute (E:\webpack\art-templte-loader\node_modules\estraverse\estraverse.js:397:31)
    at Controller.replace (E:\webpack\art-templte-loader\node_modules\estraverse\estraverse.js:637:27)
    at Object.replace (E:\webpack\art-templte-loader\node_modules\estraverse\estraverse.js:718:27)
    at precompile (E:\webpack\art-templte-loader\node_modules\art-template\lib\precompile.js:176:22)
    at Object.loader (E:\webpack\art-templte-loader\node_modules\art-template-loader\src\index.js:80:12)
 @ ./include/index.js 1:15-37
`

**Comment by rainke** [comment]
你有定义变量 title 吗

**Comment by fantasy525** [comment]
你说的title定义没有？这里不是定义了一个对象嘛{title:title}我仅仅是把官方文档里面的example中的include下面的index.art源文件改了一下，源文件是
`<% include('./header.art', {
     title: title
}) %>
{{include('./header.art',{title:title})}}
<p><img src="" ></p>
<p>This is just an awesome page.</p>
{{include './footer.art'}}`
我改成这样子

`{{include('./header.art',{title:title})}}
<p><img src="./octocat.png" alt="octocat"></p>
<p>This is just an awesome page.</p>
{{include './footer.art'}}`

**Comment by aui** [comment]
1. 请按照文档来书写模板，正确的语法为 `{{include file data}}` 或 `<% include(file, data) %>`
2. 提交问题请格式化代码
